export const getHeaderVars = (isHeroPage: boolean) =>
  isHeroPage
    ? {
        '--header-border': 'var(--pp-header-border)',
        '--header-background': 'transparent',
        '--header-backdrop': 'none',
        '--menu-button-color': 'var(--pp-menu-button-color)',
        '--menu-button-border': 'var(--pp-menu-button-border)',
        '--menu-button-background': 'var(--pp-menu-button-background)',
        '--drawer-background': 'var(--pp-drawer-background)',
        '--drawer-text-color': 'var(--pp-drawer-text-color)',
        '--drawer-divider': 'var(--pp-drawer-divider)',
        '--drawer-profile-border': 'var(--pp-drawer-profile-border)',
        '--drawer-profile-background': 'var(--pp-drawer-profile-background)',
        '--drawer-outline-color': 'var(--pp-drawer-outline-color)',
        '--drawer-outline-border': 'var(--pp-drawer-outline-border)',
        '--drawer-hover-background': 'var(--pp-drawer-hover-background)',
        '--drawer-hover-border': 'var(--pp-drawer-hover-border)',
      }
    : {
        '--header-border': 'var(--pp-header-border)',
        '--header-background': 'var(--pp-header-background)',
        '--header-backdrop': 'blur(18px)',
        '--menu-button-color': 'var(--pp-menu-button-color)',
        '--menu-button-border': 'var(--pp-menu-button-border)',
        '--menu-button-background': 'var(--pp-menu-button-background)',
        '--drawer-background': 'var(--pp-drawer-background)',
        '--drawer-text-color': 'var(--pp-drawer-text-color)',
        '--drawer-divider': 'var(--pp-drawer-divider)',
        '--drawer-profile-border': 'var(--pp-drawer-profile-border)',
        '--drawer-profile-background': 'var(--pp-drawer-profile-background)',
        '--drawer-outline-color': 'var(--pp-drawer-outline-color)',
        '--drawer-outline-border': 'var(--pp-drawer-outline-border)',
        '--drawer-hover-background': 'var(--pp-drawer-hover-background)',
        '--drawer-hover-border': 'var(--pp-drawer-hover-border)',
      };
